# Site settings
title: Nexerq - aka n2468txd
email: nexerq@gmail.com
description: Just a guy who clicks circles, does coding, and goes to school all at once.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nexerq.cf" # the base hostname & protocol for your site
twitter_username: n2468txd
github_username:  nicholastay
osu_username: Nexerq
disqus_shortname: nexerq
youtube_nickname: Nexerq # Display name
youtube_channel_id: UCL1Ifo1tPouRGYosSm6N14w # This must be the ID in /channel/ (permalink)
twitch_username: n2468txd

# Build settings
markdown: kramdown
